---
cmd:
    netbox_prod_root_url: "https://netbox.metropolis.io"
    token_key: "Token fa4f9e293395c4c1e9c23197384b4589e7a716ba"
    netbox_dev_root_url: "https://netbox-staging.metropolis.io"
    circuits:
        circuits_api_url:
            circuits_terminations: "/api/circuits/circuit-terminations/"
            circuits_terminations_id: "/api/circuits/circuit-terminations/"
            circuit_types: "/api/circuits/circuit-types/"
            circuit_types_id: "/api/circuits/circuit-types/"
            circuits: "/api/circuits/circuits/"
            circuits_id: "/api/circuits/circuits/"
            provider_accounts: "/api/circuits/provider-accounts/"
            provider_accounts_id: "/api/circuits/provider-accounts/"
            provider_networks: "/api/circuits/provider-networks/"
            provider_networks_id: "/api/circuits/provider-networks/"
            providers: "/api/circuits/providers/"
            providers_id: "/api/circuits/providers/"
    core:
        core_api_url:
            data_files: "/api/core/data-files/?limit=500"
            data_files_id: "/api/core/data-files/"
            data_sources: "/api/core/data-sources/?limit=500"
            data_sources_id: "/api/core/data-sources/"
            jobs: "/api/core/jobs/?limit=500"
            jobs_id: "/api/core/jobs/"
    dcim:
        dcim_api_url:
            cable_terminations: "/api/dcim/cable-terminations/?limit=100"
            cable_terminations_id: "/api/dcim/cable-terminations/"
            cables: "/api/dcim/cables/?limit=100"
            cables_id: "/api/dcim/cables/"
            connected_device: "/api/dcim/connected-device/?limit=100"
            connected_device_id: "/api/dcim/connected-device/"
            console_port_templates: "/api/dcim/console-port-templates/?limit=100"
            console_port_templates_id: "/api/dcim/console-port-templates/"
            console_ports: "/api/dcim/console-ports/?limit=100"
            console_ports_id: "/api/dcim/console-ports/"
            console_server_port_templates: "/api/dcim/console-server-port-templates/?limit=100"
            console_server_port_templates_id: "/api/dcim/console-server-port-templates/"
            console_server_ports: "/api/dcim/console-server-ports/?limit=100"
            console_server_ports_id: "/api/dcim/console-server-ports/"
            device_bay_templates: "/api/dcim/device-bay-templates/?limit=100"
            device_bay_templates_id: "/api/dcim/device-bay-templates/"
            device_bays: "/api/dcim/device-bays/?limit=100"
            device_bays_id: "/api/dcim/device-bays/"
            device_roles: "/api/dcim/device-roles/?limit=100"
            device_roles_id: "/api/dcim/device-roles/"
            device_types: "/api/dcim/device-types/?limit=100"
            device_types_id: "/api/dcim/device-types/"
            devices: "/api/dcim/devices/?limit=100"
            devices_id: "/api/dcim/devices/"
            devices_serial_number: "/api/dcim/devices/?serial="
            front_port_templates: "/api/dcim/front-port-templates/?limit=100"
            front_port_templates_id: "/api/dcim/front-port-templates/"
            front_ports: "/api/dcim/front-ports/?limit=100"
            front_ports_id: "/api/dcim/front-ports/"
            interface_templates: "/api/dcim/interface-templates/?limit=100"
            interface_templates_id: "/api/dcim/interface-templates/"
            interfaces: "/api/dcim/interfaces/?limit=100"
            interfaces_id: "/api/dcim/interfaces/"
            inventory_item_roles: "/api/dcim/inventory-item-roles/?limit=100"
            inventory_item_roles_id: "/api/dcim/inventory-item-roles/"
            inventory_item_templates: "/api/dcim/inventory-item-templates/?limit=100"
            inventory_item_templates_id: "/api/dcim/inventory-item-templates/"
            inventory_items: "/api/dcim/inventory-items/?limit=100"
            inventory_items_id: "/api/dcim/inventory-items/"
            locations: "/api/dcim/locations/?limit=100"
            locations_id: "/api/dcim/locations/"
            manufacturers: "/api/dcim/manufacturers/?limit=100"
            manufacturers_id: "/api/dcim/manufacturers/"
            module_bay_templates: "/api/dcim/module-bay-templates/?limit=100"
            module_bay_templates_id: "/api/dcim/module-bay-templates/"
            module_bays: "/api/dcim/module-bays/?limit=100"
            module_bays_id: "/api/dcim/module-bays/"
            module_types: "/api/dcim/module-types/?limit=100"
            module_types_id: "/api/dcim/module-types/"
            modules: "/api/dcim/modules/?limit=100"
            modules_id: "/api/dcim/modules/"
            platforms: "/api/dcim/platforms/?limit=100"
            platforms_id: "/api/dcim/platforms/"
            power_feeds: "/api/dcim/power-feeds/?limit=100"
            power_feeds_id: "/api/dcim/power-feeds/"
            power_outlet_templates: "/api/dcim/power-outlet-templates/?limit=100"
            power_outlet_templates_id: "/api/dcim/power-outlet-templates/"
            power_outlets: "/api/dcim/power-outlets/?limit=100"
            power_outlets_id: "/api/dcim/power-outlets/"
            power_panels: "/api/dcim/power-panels/?limit=100"
            power_panels_id: "/api/dcim/power-panels/"
            power_port_templates: "/api/dcim/power-port-templates/?limit=100"
            power_port_templates_id: "/api/dcim/power-port-templates/"
            power_ports: "/api/dcim/power-ports/?limit=100"
            power_ports_id: "/api/dcim/power-ports/"
            rack_reservations: "/api/dcim/rack-reservations/?limit=100"
            rack_reservations_id: "/api/dcim/rack-reservations/"
            rack_roles: "/api/dcim/rack-roles/?limit=100"
            rack_roles_id: "/api/dcim/rack-roles/"
            racks: "/api/dcim/racks/?limit=100"
            racks_id: "/api/dcim/racks/"
            rear_port_templates: "/api/dcim/rear-port-templates/?limit=100"
            rear_port_templates_id: "/api/dcim/rear-port-templates/"
            rear_ports: "/api/dcim/rear-ports/?limit=100"
            rear_ports_id: "/api/dcim/rear-ports/"
            regions: "/api/dcim/regions/?limit=100"
            regions_id: "/api/dcim/regions/"
            site_groups: "/api/dcim/site-groups/?limit=100"
            site_groups_id: "/api/dcim/site-groups/"
            sites: "/api/dcim/sites/?limit=100"
            sites_id: "/api/dcim/sites/"
            virtual_chassis: "/api/dcim/virtual-chassis/?limit=100"
            virtual_chassis_id: "/api/dcim/virtual-chassis/"
            virtual_device_contexts: "/api/dcim/virtual-device-contexts/?limit=100"
            virtual_device_contexts_id: "/api/dcim/virtual-device-contexts/"
    extras:
        extras_api_url:
            bookmarks: "/api/extras/bookmarks/"
            config_contexts: "/api/extras/config-contexts/"
            config_templates: "/api/extras/config-templates/"
            content_types: "/api/extras/content-types/"
            custom_field_choice_sets: "api/extras/custom-field-choice-sets/"
            custom_fields: "/api/extras/custom_fields/"
            custom_links: "/api/extras/custom-links/"
            dashboard: "/api/extras/dashboard/"
            event_rules: "/api/extras/event-rules/"
            export_templates: "/api/extras/export-templates/"
            image_attachments: "/api/extras/image-attachments/"
            journal_entries: "/api/extras/journal-entries/"
            object_changes: "/api/extras/object-changes/"
            saved_filters: "/api/extras/saved-filters/"
            tags: "/api/extras/tags/"
            webhooks: "/api/extras/webhooks/"
    ipam:
        ipam_api_url:
            aggregates: "/api/ipam/aggregates/?limit=100"
            aggregates_id: "/api/ipam/aggregates/"
            asn_ranges: "/api/ipam/asn-ranges/?limit=100"
            asn_ranges_id: "/api/ipam/asn-ranges/"
            asns: "/api/ipam/asns/?limit=100"
            asns_id: "/api/ipam/asns/"
            fhrp_group_assignments: "/api/ipam/fhrp-group-assignments/?limit=100"
            fhrp_group_assignments_id: "/api/ipam/fhrp-group-assignments/"
            fhrp_groups: "/api/ipam/fhrp-groups/?limit=100"
            fhrp_groups_id: "/api/ipam/fhrp-groups/"
            ip_addresses: "/api/ipam/ip-addresses/?limit=100"
            ip_addresses_id: "/api/ipam/ip-addresses/"
            ip_ranges: "/api/ipam/ip-ranges/?limit=100"
            ip_ranges_id: "/api/ipam/ip-ranges/"
            prefixes: "/api/ipam/prefixes/?limit=100"
            prefixes_id: "/api/ipam/prefixes/"
            rirs: "/api/ipam/rirs/?limit=100"
            rirs_id: "/api/ipam/rirs/"
            roles: "/api/ipam/roles/?limit=100"
            roles_id: "/api/ipam/roles/"
            route_targets: "/api/ipam/route-targets/?limit=100"
            route_targets_id: "/api/ipam/route-targets/"
            service_templates: "/api/ipam/service-templates/?limit=100"
            service_templates_id: "/api/ipam/service-templates/"
            services: "/api/ipam/services/?limit=100"
            services_id: "/api/ipam/services/"
            vlan_groups: "/api/ipam/vlan-groups/?limit=100"
            vlan_groups_id: "/api/ipam/vlan-groups/"
            vlans: "/api/ipam/vlans/?limit=100"
            vlans_id: "/api/ipam/vlans/"
            vrfs: "/api/ipam/vrfs/?limit=100"
            vrfs_id: "/api/ipam/vrfs/"
    tenancy:
        tenancy_api_url:
            contact_assignments: "/api/tenancy/contact-assignments/"
            contact_groups: "/api/tenancy/contact-groups/"
            contact_roles: "/api/tenancy/contact-roles/"
            contacts: "/api/tenancy/contacts/"
            tenant_groups: "/api/tenancy/tenant-groups/"
            tenants: "/api/tenancy/tenants/"
    users:
        users_api_url:
            config: "/api/users/config/"
            groups: "/api/users/groups/"
            permissions: "/api/users/permissions/"
            tokens: "/api/users/tokens/"
            provision: "/api/users/token/provision/"
            users: "/api/users/users/"
    virtualization:
        virtualization_api_url:
            cluster_groups: "/api/virtualization/cluster-groups/"
            cluster_types: "/api/virtualization/cluster-types/"
            clusters: "/api/virtualization/clusters/"
            interfaces: "/api/virtualization/interfaces/"
            virtual_disks: "/api/virtualization/virtual-disks/"
            virtual_machines: "/api/virtualization/virtual-machines/"
    vpn:
        vpn_api_url:
            ike_policies: "/api/vpn/ike-policies/"
            ike_proposals: "/api/vpn/ike-proposals/"
            ipsec_policies: "/api/vpn/ipsec-policies/"
            ipsec_profiles: "/api/vpn/ipsec-profiles/"
            ipsec_proposals: "/api/vpn/ipsec-proposals/"
            l2vpn_terminations: "/api/vpn/l2vpn-terminations/"
            l2vpns: "/api/vpn/l2vpns/"
            tunnel-groups: "/api/vpn/tunnel-groups/"
            tunnel-terminations: "/api/vpn/tunnel-terminations/"
            tunnels: "/api/vpn/tunnels/"
    wireless:
        wireless_api_url:
            wireless_lan_groups: "/api/wireless/wireless-lan-groups/"
            wireless_lans: "/api/wireless/wireless-lans/"
            wireless_links: "/api/wireless/wireless-links/"